### ISSUE TITLE
Fix broken images

### ISSUE THREAD

**Issue by nop33** [alephium/old-wiki#17]
Example: https://wiki.alephium.org/Full-node-on-raspberry-pi.html

![image](https://user-images.githubusercontent.com/1579899/141786079-7ae2a761-4a14-44e9-a27e-a0474213aa78.png)

**Comment by polarker** [comment]
@tdroxler maybe you could help on this ?

**Comment by nop33** [comment]
I'm looking for a solution, installing all dependencies atm
